### ISSUE TITLE
Error while training MTAN with DWA on NYUv2. Seems to be network related .

### ISSUE THREAD

**Issue by Jacky1128** [median-research-group/LibMTL#85]
General Configuration:
        Mode: train
        Wighting: DWA
        Architecture: MTAN
        Rep_Grad: False
        Multi_Input: False
        Seed: 0
        Save Path: ./logs/
        Load Path: None
        Device: cuda:1
DWA Configuration:
        T: 2.0
Optimizer Configuration:
        optim: adam
        lr: 0.0001
        weight_decay: 1e-05
Scheduler Configuration:
        scheduler: step
        step_size: 100
        gamma: 0.5
Traceback (most recent call last):
  File "/root/miniconda3/envs/mtl/lib/python3.12/site-packages/torch/cuda/__init__.py", line 306, in _lazy_init
    queued_call()
  File "/root/miniconda3/envs/mtl/lib/python3.12/site-packages/torch/cuda/__init__.py", line 174, in _check_capability
    capability = get_device_capability(d)
                 ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/miniconda3/envs/mtl/lib/python3.12/site-packages/torch/cuda/__init__.py", line 430, in get_device_capability
    prop = get_device_properties(device)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/miniconda3/envs/mtl/lib/python3.12/site-packages/torch/cuda/__init__.py", line 448, in get_device_properties
    return _get_device_properties(device)  # type: ignore[name-defined]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: device >= 0 && device < num_gpus INTERNAL ASSERT FAILED at "/opt/conda/conda-bld/pytorch_1712608847532/work/aten/src/ATen/cuda/CUDAContext.cpp":50, please report a bug to PyTorch. device=, num_gpus=

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/storage/linhaitao/wzd/LibMTL/LibMTL/architecture/MTAN.py", line 110, in __init__
    self.encoder = _transform_resnet_MTAN(self.encoder.to(device), task_name, device)
                                          ^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/miniconda3/envs/mtl/lib/python3.12/site-packages/torch/nn/modules/module.py", line 1173, in to
    return self._apply(convert)
           ^^^^^^^^^^^^^^^^^^^^
  File "/root/miniconda3/envs/mtl/lib/python3.12/site-packages/torch/nn/modules/module.py", line 779, in _apply
    module._apply(fn)
  File "/root/miniconda3/envs/mtl/lib/python3.12/site-packages/torch/nn/modules/module.py", line 804, in _apply
    param_applied = fn(param)
                    ^^^^^^^^^
  File "/root/miniconda3/envs/mtl/lib/python3.12/site-packages/torch/nn/modules/module.py", line 1159, in convert
    return t.to(
           ^^^^^
  File "/root/miniconda3/envs/mtl/lib/python3.12/site-packages/torch/cuda/__init__.py", line 312, in _lazy_init
    raise DeferredCudaCallError(msg) from e
torch.cuda.DeferredCudaCallError: CUDA call failed lazily at initialization with error: device >= 0 && device < num_gpus INTERNAL ASSERT FAILED at "/opt/conda/conda-bld/pytorch_1712608847532/work/aten/src/ATen/cuda/CUDAContext.cpp":50, please report a bug to PyTorch. device=, num_gpus=

CUDA call was originally invoked at:

  File "/storage/linhaitao/wzd/LibMTL/examples/nyu/main.py", line 1, in <module>
    import torch, argparse
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/root/miniconda3/envs/mtl/lib/python3.12/site-packages/torch/__init__.py", line 1478, in <module>
    _C._initExtension(manager_path())
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/root/miniconda3/envs/mtl/lib/python3.12/site-packages/torch/cuda/__init__.py", line 238, in <module>
    _lazy_call(_check_capability)
  File "/root/miniconda3/envs/mtl/lib/python3.12/site-packages/torch/cuda/__init__.py", line 235, in _lazy_call
    _queued_calls.append((callable, traceback.format_stack()))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/storage/linhaitao/wzd/LibMTL/examples/nyu/main.py", line 110, in <module>
    main(params)
  File "/storage/linhaitao/wzd/LibMTL/examples/nyu/main.py", line 85, in main
    NYUmodel = NYUtrainer(task_dict=task_dict, 
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/storage/linhaitao/wzd/LibMTL/examples/nyu/main.py", line 68, in __init__
    super(NYUtrainer, self).__init__(task_dict=task_dict, 
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/storage/linhaitao/wzd/LibMTL/LibMTL/trainer.py", line 94, in __init__
    self._prepare_model(weighting, architecture, encoder_class, decoders)
  File "/storage/linhaitao/wzd/LibMTL/LibMTL/trainer.py", line 109, in _prepare_model
    self.model = MTLmodel(task_name=self.task_name, 
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/storage/linhaitao/wzd/LibMTL/LibMTL/trainer.py", line 106, in __init__
    super(MTLmodel, self).__init__(task_name, encoder_class, decoders, rep_grad, multi_input, device, **kwargs)
  File "/storage/linhaitao/wzd/LibMTL/LibMTL/architecture/MTAN.py", line 112, in __init__
    self.encoder.resnet_network = _transform_resnet_MTAN(self.encoder.resnet_network.to(device), task_name, device)
                                                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/miniconda3/envs/mtl/lib/python3.12/site-packages/torch/nn/modules/module.py", line 1709, in __getattr__
    raise AttributeError(f"'{type(self).__name__}' object has no attribute '{name}'")
AttributeError: 'ResnetDilated' object has no attribute 'resnet_network'

**Comment by Baijiong-Lin** [comment]
I have tested it again and there were no errors.

<img width="946" alt="image" src="https://github.com/user-attachments/assets/9a2de70d-4477-443d-9367-d0016beaab70">

**Comment by Jacky1128** [comment]
Thank you for getting back to me so quickly. I've tried again and found that the issue was likely caused by the package version mismatch in my environment (torch 2.3.0 with Python 3.12). I've rebuilt the environment, and everything is working correctly now.

Greatly appreciate your support. Your codebase is truly excellent and helpful. Thank you again for your valuable work.
